# Generated by Django 5.0.6 on 2026-06-06 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgingStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='库位编号')),
                ('area', models.CharField(max_length=100, verbose_name='库区')),
                ('row', models.CharField(blank=True, max_length=20, verbose_name='排号')),
                ('shelf', models.CharField(blank=True, max_length=20, verbose_name='架号')),
                ('capacity', models.IntegerField(default=0, verbose_name='最大容量(坛)')),
                ('used_count', models.IntegerField(default=0, verbose_name='已用数量')),
                ('temperature_req', models.FloatField(blank=True, null=True, verbose_name='要求温度(℃)')),
                ('humidity_req', models.FloatField(blank=True, null=True, verbose_name='要求湿度(%)')),
                ('status', models.CharField(choices=[('aging', '陈酿中'), ('bottled', '已装瓶'), ('sold', '已出库')], default='aging', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'aging_storage',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CellarPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='窖池编号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='窖池名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('volume', models.FloatField(default=0, verbose_name='容量(kg)')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('fermenting', '发酵中'), ('cleaning', '清洁中'), ('maintenance', '维护中')], default='idle', max_length=20, verbose_name='状态')),
                ('built_year', models.IntegerField(blank=True, null=True, verbose_name='建造年份')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'cellar_pool',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AgingEnvRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('temperature', models.FloatField(verbose_name='温度(℃)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='记录人')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_records', to='fermentation.agingstorage', verbose_name='库位')),
            ],
            options={
                'db_table': 'aging_env_record',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='FermentationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('grain_ratio', models.JSONField(default=dict, help_text='如: {"高粱": 60, "小麦": 30, "玉米": 10}', verbose_name='粮食配比')),
                ('grain_total', models.FloatField(default=0, verbose_name='粮食总重量(kg)')),
                ('yeast_type', models.CharField(max_length=100, verbose_name='酒曲类型')),
                ('yeast_amount', models.FloatField(default=0, verbose_name='酒曲用量(kg)')),
                ('entry_temperature', models.FloatField(verbose_name='入窖温度(℃)')),
                ('entry_date', models.DateTimeField(verbose_name='入窖时间')),
                ('expected_days', models.IntegerField(default=30, verbose_name='预计发酵天数')),
                ('status', models.CharField(choices=[('fermenting', '发酵中'), ('completed', '已出酒'), ('aborted', '已终止')], default='fermenting', max_length=20, verbose_name='状态')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='出窖时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cellar_pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='fermentation.cellarpool', verbose_name='窖池')),
            ],
            options={
                'db_table': 'fermentation_batch',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='FermentationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='检测时间')),
                ('cellar_temp', models.FloatField(verbose_name='窖温(℃)')),
                ('acidity', models.FloatField(verbose_name='酸度')),
                ('alcohol', models.FloatField(verbose_name='酒度(度)')),
                ('ambient_temp', models.FloatField(blank=True, null=True, verbose_name='环境温度(℃)')),
                ('ambient_humidity', models.FloatField(blank=True, null=True, verbose_name='环境湿度(%)')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='检测人')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_note', models.CharField(blank=True, max_length=200, verbose_name='异常说明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fermentation.fermentationbatch', verbose_name='批次')),
            ],
            options={
                'db_table': 'fermentation_record',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='WineQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_date', models.DateField(verbose_name='出酒日期')),
                ('total_output', models.FloatField(verbose_name='出酒总量(kg)')),
                ('grade', models.CharField(choices=[('premium', '优级'), ('grade1', '一级'), ('grade2', '二级'), ('substandard', '不合格')], max_length=20, verbose_name='酒质等级')),
                ('alcohol_content', models.FloatField(verbose_name='酒精度(度)')),
                ('acidity', models.FloatField(verbose_name='总酸(g/L)')),
                ('ester', models.FloatField(verbose_name='总酯(g/L)')),
                ('sensory_score', models.FloatField(default=0, verbose_name='感官评分')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='陈酿位置')),
                ('tasting_notes', models.TextField(blank=True, verbose_name='品鉴记录')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='fermentation.fermentationbatch', verbose_name='批次')),
            ],
            options={
                'db_table': 'wine_quality',
                'ordering': ['-produce_date'],
            },
        ),
        migrations.CreateModel(
            name='AgingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='入储日期')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='预计陈酿结束日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='出储日期')),
                ('initial_volume', models.FloatField(default=0, verbose_name='初始容量(L)')),
                ('current_volume', models.FloatField(default=0, verbose_name='当前容量(L)')),
                ('container_count', models.IntegerField(default=1, verbose_name='容器数量(坛)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在储')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='fermentation.agingstorage', verbose_name='库位')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_records', to='fermentation.winequality', verbose_name='酒质批次')),
            ],
            options={
                'db_table': 'aging_record',
                'ordering': ['-start_date'],
            },
        ),
    ]
