# Generated by Django 5.0.6 on 2026-06-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationbatch',
            name='disposal_note',
            field=models.TextField(blank=True, verbose_name='处置说明'),
        ),
        migrations.AddField(
            model_name='fermentationbatch',
            name='disposal_status',
            field=models.CharField(choices=[('none', '无需处置'), ('pending', '待处置'), ('processing', '处置中'), ('completed', '已处置待复核'), ('reviewed', '复核通过'), ('returned', '复核退回')], default='none', max_length=20, verbose_name='处置状态'),
        ),
        migrations.AddField(
            model_name='fermentationbatch',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='fermentationbatch',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复核时间'),
        ),
        migrations.AddField(
            model_name='fermentationbatch',
            name='risk_level',
            field=models.CharField(choices=[('none', '无风险'), ('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='none', max_length=20, verbose_name='风险等级'),
        ),
        migrations.CreateModel(
            name='DisposalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('source', models.CharField(choices=[('fermentation', '发酵检测异常'), ('aging_env', '陈酿温湿度异常'), ('manual', '人工创建')], default='manual', max_length=20, verbose_name='风险来源')),
                ('risk_level', models.CharField(choices=[('none', '无风险'), ('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='风险描述')),
                ('abnormal_record_id', models.IntegerField(blank=True, null=True, verbose_name='关联异常记录ID')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='责任人(酿酒师)')),
                ('status', models.CharField(choices=[('pending', '待处置'), ('processing', '处置中'), ('completed', '已处置待复核'), ('reviewed', '复核通过'), ('returned', '复核退回')], default='pending', max_length=20, verbose_name='状态')),
                ('disposal_measures', models.TextField(blank=True, verbose_name='处置措施')),
                ('disposal_person', models.CharField(blank=True, max_length=50, verbose_name='处置人')),
                ('disposal_time', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('review_opinion', models.TextField(blank=True, verbose_name='复核意见')),
                ('reviewer', models.CharField(blank=True, max_length=50, verbose_name='复核人')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposal_tasks', to='fermentation.fermentationbatch', verbose_name='发酵批次')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposal_tasks', to='fermentation.agingstorage', verbose_name='陈酿库位')),
            ],
            options={
                'db_table': 'disposal_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
